name: VewDockerAction
description: Easily builds and publishes Docker images. See readme.md at VewTech/Vew-Docker-Action

inputs:
  context:
    description: The context used for the "docker build" command.
    required: true
  dockerfile:
    description: The dockerfile used for the "docker build" command.
    required: true
  image_name:
    description: The name of the image to publish
    required: true
  image_tag:
    description: The tag that will be applied to the image, as well as 'latest'
    required: false
    default: default
  registry:
    description: The registry where the image will be uploaded.
    required: false
  registry-user:
    description: The username used for the login.
    required: false
  registry-password:
    description: The password used for the login to the registry.
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Login to Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.registry-user }}
        password: ${{ inputs.registry-password }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ${{ github.events.inputs.context }}
        file: ${{ inputs.dockerfile }}
        push: true
        tags: |
          ${{ inputs.registry }}/${{ inputs.image_name }}:${{ inputs.image_tag }}
          ${{ inputs.registry }}/${{ inputs.image_name }}:latest
