name: VewDockerAction
description: Easily builds and publishes Docker images. See readme.md at VewTech/Vew-Docker-Action

on:
  workflow_dispatch:
    inputs:
      context:
        description: The context used for the "docker build" command.
        required: true
      dockerfile:
        description: The dockerfile used for the "docker build" command.
        required: true
      image_name:
        description: The name of the image to publish
        required: true
      image_tag:
        description: The tag that will be applied to the image, as well as 'latest'
        required: false
        default: default
      push:
        description: Whether the image will be pushed to the registry or not
        required: true
      registry:
        description: The registry where the image will be uploaded.
        required: false
      registry-user:
        description: The username used for the login.
        required: false
      registry-password:
        description: The password used for the login to the registry.
        required: false
    
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Build Docker image
      uses: docker/build-push-action@v2
      if: ${{ github.event.inputs.push == false }}
      with:
        context: ${{ github.event.inputs.context }}
        file: ${{ github.event.inputs.dockerfile }}
        push: false
        tags: ${{ github.event.inputs.image_name }}:${{ github.sha }}
        
    - name: Login to Registry
      if: ${{ github.event.inputs.push == true }}
      uses: docker/login-action@v1
      with:
        registry: ${{ github.event.inputs.registry }}
        username: ${{ github.event.inputs.registry-user }}
        password: ${{ github.event.inputs.registry-password }}
        
    - name: Build and Push Docker image
      if: ${{ github.event.inputs.push == true }}
      uses: docker/build-push-action@v2
      with:
        context: ${{ github.events.inputs.context }}
        file: ${{ github.event.inputs.dockerfile }}
        push: true
        tags: |
          ${{ github.event.inputs.registry }}/${{ github.event.inputs.image_name }}:${{ github.event.release.tag_name }}
          ${{ github.event.inputs.registry }}/${{ github.event.inputs.image_name }}:latest
