name: VewDockerAction

env:
  CONTEXT: .
  DOCKERFILE: Dockerfile
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
jobs:
  build-and-publish:
  
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Test
      run: echo ${{ env.VERSION }}
      
    - name: Convert repo name to lowercase
      id: toLowerCase
      run: echo "::set-output name=lowerCaseValue::${IMAGE_NAME,,}"
      env:
        UPPERCASE_VAR: ${{ env.IMAGE_NAME }}
      
    - name: Build Docker image
      uses: docker/build-push-action@v2
      if: github.event_name != 'release'
      with:
        context: ${{ env.CONTEXT }}
        file: ${{ env.DOCKERFILE }}
        push: false
        tags: ${{steps.toLowerCase.outputs.lowerCaseValue}}:${{ github.sha }}

    - name: Login to Registry
      if: github.event_name == 'release'
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and Push Docker image
      if: github.event_name == 'release'
      uses: docker/build-push-action@v2
      with:
        context: ${{ env.CONTEXT }}
        file: ${{ env.DOCKERFILE }}
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{steps.toLowerCase.outputs.lowerCaseValue}}:${{ github.event.release.tag_name }}
          ${{ env.REGISTRY }}/${{steps.toLowerCase.outputs.lowerCaseValue}}:latest
