name: VewDockerAction
description: Easily builds and publishes Docker images. See readme.md at VewTech/Vew-Docker-Action

on:
  workflow_dispatch:
    inputs:
      context:
        description: The context used for the "docker build" command.
        required: true
      dockerfile:
        description: The dockerfile used for the "docker build" command.
        required: true
      image_name:
        description: The name of the image to publish
        required: true
      registry:
        description: The registry where the image will be uploaded.
        required: true
      registry-user:
        description: The username used for the login.
        required: true
      registry-password:
        description: The password used for the login to the registry.
        required: true
    
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build Docker image
      uses: docker/build-push-action@v2
      if: github.event_name != 'release'
      with:
        context: ${{ github.events.inputs.context }}
        file: ${{ github.events.inputs.dockerfile }}
        push: false
        tags: ${{ github.events.inputs.image_name }}:${{ github.sha }}
    - name: Login to Registry
      if: github.event_name == 'release'
      uses: docker/login-action@v1
      with:
        registry: ${{ github.events.inputs.registry }}
        username: ${{ github.events.inputs.registry-user }}
        password: ${{ github.events.inputs.registry-password }}
    - name: Build and Push Docker image
      if: github.event_name == 'release'
      uses: docker/build-push-action@v2
      with:
        context: ${{ github.events.inputs.context }}
        file: ${{ github.events.inputs.dockerfile }}
        push: true
        tags: |
          ${{ github.events.inputs.registry }}/${{ github.events.inputs.image_name }}:${{ github.event.release.tag_name }}
          ${{ github.events.inputs.registry }}/${{ github.events.inputs.image_name }}:latest
